// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	multipart "mime/multipart"

	mock "github.com/stretchr/testify/mock"

	submission "github.com/ALTA-CAPSTONE-GROUP1/e-proposal-BE/feature/submission"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

// AddSubmissionLogic provides a mock function with given fields: newSub, subFile
func (_m *UseCase) AddSubmissionLogic(newSub submission.AddSubmissionCore, subFile *multipart.FileHeader) error {
	ret := _m.Called(newSub, subFile)

	var r0 error
	if rf, ok := ret.Get(0).(func(submission.AddSubmissionCore, *multipart.FileHeader) error); ok {
		r0 = rf(newSub, subFile)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteSubmissionLogic provides a mock function with given fields: submissionID, userID
func (_m *UseCase) DeleteSubmissionLogic(submissionID int, userID string) error {
	ret := _m.Called(submissionID, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, string) error); ok {
		r0 = rf(submissionID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindRequirementLogic provides a mock function with given fields: userID, typeName, value
func (_m *UseCase) FindRequirementLogic(userID string, typeName string, value int) (submission.Core, error) {
	ret := _m.Called(userID, typeName, value)

	var r0 submission.Core
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, int) (submission.Core, error)); ok {
		return rf(userID, typeName, value)
	}
	if rf, ok := ret.Get(0).(func(string, string, int) submission.Core); ok {
		r0 = rf(userID, typeName, value)
	} else {
		r0 = ret.Get(0).(submission.Core)
	}

	if rf, ok := ret.Get(1).(func(string, string, int) error); ok {
		r1 = rf(userID, typeName, value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllSubmissionLogic provides a mock function with given fields: userID, pr
func (_m *UseCase) GetAllSubmissionLogic(userID string, pr submission.GetAllQueryParams) ([]submission.AllSubmiisionCore, []submission.SubTypeChoices, error) {
	ret := _m.Called(userID, pr)

	var r0 []submission.AllSubmiisionCore
	var r1 []submission.SubTypeChoices
	var r2 error
	if rf, ok := ret.Get(0).(func(string, submission.GetAllQueryParams) ([]submission.AllSubmiisionCore, []submission.SubTypeChoices, error)); ok {
		return rf(userID, pr)
	}
	if rf, ok := ret.Get(0).(func(string, submission.GetAllQueryParams) []submission.AllSubmiisionCore); ok {
		r0 = rf(userID, pr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]submission.AllSubmiisionCore)
		}
	}

	if rf, ok := ret.Get(1).(func(string, submission.GetAllQueryParams) []submission.SubTypeChoices); ok {
		r1 = rf(userID, pr)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]submission.SubTypeChoices)
		}
	}

	if rf, ok := ret.Get(2).(func(string, submission.GetAllQueryParams) error); ok {
		r2 = rf(userID, pr)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetSubmissionByIDLogic provides a mock function with given fields: submissionID, userID
func (_m *UseCase) GetSubmissionByIDLogic(submissionID int, userID string) (submission.GetSubmissionByIDCore, error) {
	ret := _m.Called(submissionID, userID)

	var r0 submission.GetSubmissionByIDCore
	var r1 error
	if rf, ok := ret.Get(0).(func(int, string) (submission.GetSubmissionByIDCore, error)); ok {
		return rf(submissionID, userID)
	}
	if rf, ok := ret.Get(0).(func(int, string) submission.GetSubmissionByIDCore); ok {
		r0 = rf(submissionID, userID)
	} else {
		r0 = ret.Get(0).(submission.GetSubmissionByIDCore)
	}

	if rf, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = rf(submissionID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateDataByOwnerLogic provides a mock function with given fields: updatedata, subFile
func (_m *UseCase) UpdateDataByOwnerLogic(updatedata submission.UpdateCore, subFile *multipart.FileHeader) error {
	ret := _m.Called(updatedata, subFile)

	var r0 error
	if rf, ok := ret.Get(0).(func(submission.UpdateCore, *multipart.FileHeader) error); ok {
		r0 = rf(updatedata, subFile)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewUseCase interface {
	mock.TestingT
	Cleanup(func())
}

// NewUseCase creates a new instance of UseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUseCase(t mockConstructorTestingTNewUseCase) *UseCase {
	mock := &UseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
