// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	office "github.com/ALTA-CAPSTONE-GROUP1/e-proposal-BE/feature/admin/office"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// DeleteOffice provides a mock function with given fields: id
func (_m *Repository) DeleteOffice(id uint) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllOffice provides a mock function with given fields: limit, offset, search
func (_m *Repository) GetAllOffice(limit int, offset int, search string) ([]office.Core, error) {
	ret := _m.Called(limit, offset, search)

	var r0 []office.Core
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, string) ([]office.Core, error)); ok {
		return rf(limit, offset, search)
	}
	if rf, ok := ret.Get(0).(func(int, int, string) []office.Core); ok {
		r0 = rf(limit, offset, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]office.Core)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, string) error); ok {
		r1 = rf(limit, offset, search)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertOffice provides a mock function with given fields: newOffice
func (_m *Repository) InsertOffice(newOffice office.Core) error {
	ret := _m.Called(newOffice)

	var r0 error
	if rf, ok := ret.Get(0).(func(office.Core) error); ok {
		r0 = rf(newOffice)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
