// Code generated by mockery v2.26.1. DO NOT EDIT.

package mocks

import (
	user "github.com/ALTA-CAPSTONE-GROUP1/e-proposal-BE/feature/admin/user"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CheckUserIDExists provides a mock function with given fields: id
func (_m *Repository) CheckUserIDExists(id string) (bool, error) {
	ret := _m.Called(id)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteUser provides a mock function with given fields: id
func (_m *Repository) DeleteUser(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GenerateIDFromPositionTag provides a mock function with given fields: positionTag
func (_m *Repository) GenerateIDFromPositionTag(positionTag string) (string, error) {
	ret := _m.Called(positionTag)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(positionTag)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(positionTag)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(positionTag)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPositionTagByID provides a mock function with given fields: positionID
func (_m *Repository) GetPositionTagByID(positionID int) (string, error) {
	ret := _m.Called(positionID)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (string, error)); ok {
		return rf(positionID)
	}
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(positionID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(positionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserById provides a mock function with given fields: id
func (_m *Repository) GetUserById(id string) (user.Core, error) {
	ret := _m.Called(id)

	var r0 user.Core
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (user.Core, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) user.Core); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(user.Core)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertUser provides a mock function with given fields: newUser
func (_m *Repository) InsertUser(newUser user.Core) error {
	ret := _m.Called(newUser)

	var r0 error
	if rf, ok := ret.Get(0).(func(user.Core) error); ok {
		r0 = rf(newUser)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SelectAllUser provides a mock function with given fields: limit, offset, name
func (_m *Repository) SelectAllUser(limit int, offset int, name string) ([]user.Core, error) {
	ret := _m.Called(limit, offset, name)

	var r0 []user.Core
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, string) ([]user.Core, error)); ok {
		return rf(limit, offset, name)
	}
	if rf, ok := ret.Get(0).(func(int, int, string) []user.Core); ok {
		r0 = rf(limit, offset, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.Core)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, string) error); ok {
		r1 = rf(limit, offset, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUser provides a mock function with given fields: id, input
func (_m *Repository) UpdateUser(id string, input user.Core) error {
	ret := _m.Called(id, input)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, user.Core) error); ok {
		r0 = rf(id, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
