// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	position "github.com/ALTA-CAPSTONE-GROUP1/e-proposal-BE/feature/admin/position"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetPositions provides a mock function with given fields: limit, offset, search
func (_m *Repository) GetPositions(limit int, offset int, search string) ([]position.Core, error) {
	ret := _m.Called(limit, offset, search)

	var r0 []position.Core
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, string) ([]position.Core, error)); ok {
		return rf(limit, offset, search)
	}
	if rf, ok := ret.Get(0).(func(int, int, string) []position.Core); ok {
		r0 = rf(limit, offset, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]position.Core)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, string) error); ok {
		r1 = rf(limit, offset, search)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertPosition provides a mock function with given fields: newPosition
func (_m *Repository) InsertPosition(newPosition position.Core) error {
	ret := _m.Called(newPosition)

	var r0 error
	if rf, ok := ret.Get(0).(func(position.Core) error); ok {
		r0 = rf(newPosition)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
