// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	position "github.com/ALTA-CAPSTONE-GROUP1/e-proposal-BE/feature/admin/position"
	mock "github.com/stretchr/testify/mock"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

// AddPositionLogic provides a mock function with given fields: newPosition
func (_m *UseCase) AddPositionLogic(newPosition position.Core) error {
	ret := _m.Called(newPosition)

	var r0 error
	if rf, ok := ret.Get(0).(func(position.Core) error); ok {
		r0 = rf(newPosition)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewUseCase interface {
	mock.TestingT
	Cleanup(func())
}

// NewUseCase creates a new instance of UseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUseCase(t mockConstructorTestingTNewUseCase) *UseCase {
	mock := &UseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
