// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	cc "github.com/ALTA-CAPSTONE-GROUP1/e-proposal-BE/feature/user/cc"
	mock "github.com/stretchr/testify/mock"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

// GetAllCcLogic provides a mock function with given fields: userID
func (_m *UseCase) GetAllCcLogic(userID string) ([]cc.CcCore, error) {
	ret := _m.Called(userID)

	var r0 []cc.CcCore
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]cc.CcCore, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) []cc.CcCore); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]cc.CcCore)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUseCase interface {
	mock.TestingT
	Cleanup(func())
}

// NewUseCase creates a new instance of UseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUseCase(t mockConstructorTestingTNewUseCase) *UseCase {
	mock := &UseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
