// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	subtype "github.com/ALTA-CAPSTONE-GROUP1/e-proposal-BE/feature/admin/subtype"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetSubTypes provides a mock function with given fields: limit, offset, search
func (_m *Repository) GetSubTypes(limit int, offset int, search string) ([]subtype.GetSubmissionTypeCore, []subtype.GetPosition, error) {
	ret := _m.Called(limit, offset, search)

	var r0 []subtype.GetSubmissionTypeCore
	var r1 []subtype.GetPosition
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int, string) ([]subtype.GetSubmissionTypeCore, []subtype.GetPosition, error)); ok {
		return rf(limit, offset, search)
	}
	if rf, ok := ret.Get(0).(func(int, int, string) []subtype.GetSubmissionTypeCore); ok {
		r0 = rf(limit, offset, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]subtype.GetSubmissionTypeCore)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, string) []subtype.GetPosition); ok {
		r1 = rf(limit, offset, search)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]subtype.GetPosition)
		}
	}

	if rf, ok := ret.Get(2).(func(int, int, string) error); ok {
		r2 = rf(limit, offset, search)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// InsertSubType provides a mock function with given fields: req
func (_m *Repository) InsertSubType(req subtype.RepoData) error {
	ret := _m.Called(req)

	var r0 error
	if rf, ok := ret.Get(0).(func(subtype.RepoData) error); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
